site_name: Nawaz Y. khan (Data Engineer/Data Scientist/Machine Learning Engineer)
site_description: A collection of my projects
site_author: Nawaz Y. khan

theme:
  name: material
  language: en
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.action.edit
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: cyan
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: cyan
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    repo: fontawesome/brands/github

nav:
  - Home: index.md
  - Projects: projects.md
  # - Projects Details:
      # - Project 1: projects/project_1.md
      # - Project 2: projects/project_2.md
      # - Project 3: projects/project_3.md
      # - Project 4: projects/project_4.md
  - Blogs: blogs.md
  - Skills: skills.md
  - Resume: resume.md
  - About: about.md

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.tabbed:
      alternate_style: true
  - footnotes

plugins:
  - search
  # REMOVE this line below – it's incorrect and causes errors
  # - mkdocs-material

extra_css:
  - stylesheets/extra.css  # Optional: Add your own CSS styles here

extra_javascript:
  - javascripts/extra.js   # Optional: Add your own JS scripts here
